# Ta-Lib function mapping class 
# Function: 'T3'
# Description: 'Triple Exponential Moving Average (T3)'
# This file has been autogenerated - Do Not Edit.
class Indicator::AutoGen::T3 < Indicator::Base
  # Time Period <Integer>
  attr_accessor :time_period
  # Volume Factor <Double>
  attr_accessor :volume_factor

  def initialize(*args)
    if args.first.is_a? Hash
      h = args.first
      @time_period = h[:time_period] || 5
      @volume_factor = h[:volume_factor] || 7.000000e-1
    else
      @time_period = args[0] || 5 
      @volume_factor = args[1] || 7.000000e-1 
    end
    
    @func = TaLib::Function.new("T3")
  end

  # Is price data required as an input
  def self.price_input?
    false
  end

  # The list of arguments
  def self.arguments
    [ :time_period, :volume_factor ]
  end

  # The minimum set of inputs required
  def self.inputs
    [ :in_real ]
  end

  # The outputs generated by this function
  def self.outputs
    [ :out_real ]
  end

  def run(in_real)
    len = in_real.length
    @func.in_real(0, map(in_real))

    @func.opt_int(0, @time_period)
    @func.opt_real(1, @volume_factor)

    out_real = Array.new(len)
    @func.out_real(0, out_real)
  
    @func.call(0, len - 1)

    out_real
  end
end
